### PR TITLE
Modify affiliation

### PR DESCRIPTION
**Pull request by wuyingjun-lucky**
**What type of PR is this?**

**What this PR does / why we need it**:
Modify Affiliation
**Which issue(s) this PR fixes**:
Fixes #
NONE
**Special notes for your reviewer**:

### CODE REVIEW

**Review by RainbowMango — APPROVED** [review]
/approve

@wuyingjun-lucky Just a reminder, you might need to update the affiliation info to CNCF too.
I see that the `Company` is empty on [CNCF Developer Activity Counts by Companies](https://karmada.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1).
Here is some guideline you can refer to:
https://karmada.io/docs/next/contributor/count-contributions/

**Comment by wuyingjun-lucky** [comment]
> 

Thanks for reminding me.

**Comment by wuyingjun-lucky** [comment]
> /approve
> 
> @wuyingjun-lucky Just a reminder, you might need to update the affiliation info to CNCF too. I see that the `Company` is empty on [CNCF Developer Activity Counts by Companies](https://karmada.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1). Here is some guideline you can refer to: https://karmada.io/docs/next/contributor/count-contributions/

Thanks for reminding me.

**Pull request merged**
