### PR TITLE
add windsonsea to doc-reviewer

### PR DESCRIPTION
**Pull request by windsonsea**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

I joined Karmada one year ago and have actively contributed to the project. By this time, I have [authored 24 PRs](https://github.com/karmada-io/website/pulls/windsonsea), and I have also [reviewed 17 PRs](https://github.com/karmada-io/website/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3A%40me).

Recently, with the increase in en-zh PRs, I have noticed that the review process is not always timely. To address this, I would like to take on the responsibility of improving the documentation, particularly for Chinese content, in order to provide convenience for native Chinese developers.

As a technical writer, I find great joy in reading and working with both English and Chinese text during the process of writing, translating, and reviewing. I value the opportunity to learn from the texts you have provided in each PR related to the documentation.

I appreciate the honor of being entrusted with this responsibility and look forward to continuing my contribution to enhancing the quality of the documentation.

Thanks.

### CODE REVIEW

**Comment by windsonsea** [comment]
cc @RainbowMango @Poor12

**Review by RainbowMango — COMMENTED** [review]
LGTM

Please send a PR to the website repo and put your name on the owner list.

**Comment by windsonsea** [comment]
lol, thanks. Will open a PR there soon.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
