### PR TITLE
add KubeDay Israel 2023 talk about Karmada

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

add KubeDay Israel 2023 talk about Karmada: Simplifying Multi-cluster Kubernetes Management with Karmada - Eliran Bivas, AppsFlyer

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

/cc @bivas

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @bivas, thanks for your brilliant talk and we can see that the enthusiasm of many audience members for Karmada. 

Thank you for sharing. 👍

**Comment by bivas** [comment]
I'm honored 🙏🏼 
Even after the talk has ended, I spend additional hour to talk to people and discuss their use cases.
I encouraged them to try and contribute to the project.

Thank you for working and enhancing this project

**Review by RainbowMango — APPROVED** [review]
/approve

Thanks, that means a lot to the community.

**Pull request merged**
